services:
  app:
    container_name: google_api
    build: .
    env_file:
      - ./envs/postgres.env
      - ./envs/app.env
    entrypoint: [ "sh", "entrypoint.sh" ]
    depends_on:
      - postgres
    user: app

  postgres:
    container_name: google_api-postgres
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/postgres.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
